name: Monitor Notion Database
on:
  schedule:
    - cron: "*/6 * * * *"  # 매 6분마다 실행
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run Notion monitor script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          LAST_CHECK_TIME: ${{ vars.LAST_CHECK_TIME }}
        run: python notion_monitor.py

      - name: Update last check time
        if: success()
        run: |
          echo "LAST_CHECK_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
