name: Notion Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install requests

    - name: Check if last_check_time.txt exists
      run: |
        if [ -f /home/runner/work/notion-automation/notion-automation/last_check_time.txt ]; then
          echo "Last check time file exists"
          cat /home/runner/work/notion-automation/notion-automation/last_check_time.txt
        else
          echo "Last check time file does not exist. Creating a new one."
          echo "2021-01-01T00:00:00.000Z" > /home/runner/work/notion-automation/notion-automation/last_check_time.txt

    - name: Run Notion monitor script
      run: python notion_monitor.py
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Save last check time to environment
      run: echo "LAST_CHECK_TIME=$(cat /home/runner/work/notion-automation/notion-automation/last_check_time.txt)" >> $GITHUB_ENV

    - name: Upload last check time
      uses: actions/upload-artifact@v2
      with:
        name: last-check-time
        path: /home/runner/work/notion-automation/notion-automation/last_check_time.txt
